### ISSUE TITLE
csv output bug

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/csirtg-indicator-py#13]

**Comment by wesyoung** [comment]
```
(cifv3)bender:bearded-avenger wes$ cif --itype ipv4 --remote http://localhost:5000 --format csv
2016-09-15 11:57:14,314 - INFO - cifsdk.client[126][MainThread] - searching for ipv4
2016-09-15 11:57:14,327 - INFO - requests.packages.urllib3.connectionpool[207][MainThread] - Starting new HTTP connection (1): localhost
Traceback (most recent call last):
  File "/Users/wes/.virtualenvs/cifv3/bin/cif", line 9, in <module>
    load_entry_point('cifsdk', 'console_scripts', 'cif')()
  File "/Users/wes/Development/csirtg/bearded-avenger-sdk-py/cifsdk/client/__init__.py", line 141, in main
    print(FORMATS[options.get('format')](data=rv))
  File "/Users/wes/Development/csirtg/bearded-avenger-sdk-py/cifsdk/format/zcsv.py", line 31, in __repr__
    r[c] = y.replace('\n', r'\\n')
AttributeError: 'int' object has no attribute 'replace'
```
